import {
  Building2,
  CircleHelp,
  Coins,
  DollarSign,
  Facebook,
  IdCard,
  Instagram,
  Linkedin,
  Lock,
  Mail,
  Dumbbell,
  Flame,
  Star,
  ShieldCheck,
  BarChart,
  Bike,
  Waves,
  TreePalm,
  Moon,
  Phone,
  Twitter,
  User,
  Youtube,
} from 'lucide-react';
export const iconMap: any = {
  DollarSign: <DollarSign className="icon" />,
  Coins: <Coins className="icon" />,
  email: <Mail className="icon" />,
  lock: <Lock className="icon" />,
  user: <User className="icon" />,
  help: <CircleHelp className="icon" />,
  phone: <Phone className="icon" />,
  building: <Building2 className="icon" />,
  'id-card': <IdCard className="icon" />,
  dumbbel: <Dumbbell className="icon" />,
  flame: <Flame className="icon" />,
  star: <Star className="icon" />,
  shield: <ShieldCheck className="icon" />,
  'bar-chart': <BarChart className="icon" />,
  bike: <Bike className="icon" />,
  wave: <Waves className="icon" />,
  tree: <TreePalm className="icon" />,
  moon: <Moon className="icon" />,
  //Social media icons
  facebook: <Facebook className="icon" />,
  twitter: <Twitter className="icon" />,
  linkedin: <Linkedin className="icon" />,
  youtube: <Youtube className="icon" />,
  instagram: <Instagram className="icon" />,
};
